#!/bin/bash

# Script to help download placeholder images for the InstaBuild app
# You can use free image sources like:
# - Unsplash: https://unsplash.com/
# - Pexels: https://www.pexels.com/
# - Pixabay: https://pixabay.com/

echo "InstaBuild - Image Download Helper"
echo "==================================="
echo ""
echo "Please download images for the following categories and products:"
echo ""
echo "Category Images (Save to: assets/images/categories/)"
echo "  - appliances.png"
echo "  - appliances_parts.png"
echo "  - bath.png"
echo "  - drywall.png"
echo "  - electrical.png"
echo "  - fencing.png"
echo "  - flooring.png"
echo "  - gutters.png"
echo ""
echo "Product Images (Save to: assets/images/products/)"
echo "  - refrigerator.png"
echo "  - washing_machine.png"
echo "  - microwave.png"
echo "  - water_filter.png"
echo "  - washing_belt.png"
echo "  - bathtub.png"
echo "  - shower_head.png"
echo "  - faucet.png"
echo "  - drywall_sheet.png"
echo "  - joint_compound.png"
echo "  - led_bulbs.png"
echo "  - electrical_wire.png"
echo "  - circuit_breaker.png"
echo "  - vinyl_siding.png"
echo "  - fence_posts.png"
echo "  - laminate_flooring.png"
echo "  - carpet_tiles.png"
echo "  - vinyl_plank.png"
echo "  - rain_gutters.png"
echo "  - downspouts.png"
echo ""
echo "Logo Image (Save to: assets/images/logo/)"
echo "  - logo.png"
echo ""
echo "Suggested image sources:"
echo "  - Unsplash: https://unsplash.com/ (Free, no attribution required)"
echo "  - Pexels: https://www.pexels.com/ (Free, no attribution required)"
echo "  - Pixabay: https://pixabay.com/ (Free)"
echo ""
echo "The app will display fallback icons if images are not found."
echo "Add your images to the respective folders and run 'flutter run' again."
